Add JsProxy.to_py method
iodide-project/pyodide pull request #1244
Opened 2021-02-12 16:31 UTC by hoodmane

Currently converts `Map` to `dict`, `Set` to `set` and array-like objects to `list`. If the object is a base `Object` (not a subclass of `Object`, I check that `Object.constructor.name === "object"` and that it doesn't have a custom `Symbol.toStringTag`) then I convert it to a `dict` as well. Otherwise I leave it alone.

Takes a depth parameter which works in the same way as `PyProxy.toJs`.

Comparing the Python [Concrete Objects Layer](https://docs.python.org/3/c-api/concrete.html) to the list of [Javascript builtins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) it looks to me like the one remaining candidate for conversions is we could convert python `DateTime` objects with Javascript `Date` objects.

2021-02-12 18:58 UTC, hoodmane commented
Here's one limitation of the current implementation:
```javascript
z = new Map();
z.set([1,1], 2);
pyodide.runPython(`
    from js import z
    z.to_py()
`)
```
Raises `TypeError: unhashable type: 'list'`.

2021-02-13 08:36 UTC, rth commented
> Here's one limitation of the current implementation:
> TypeError: unhashable type

I think that's an expected error from the Python perspective on unhashable keys, so better to raise it than try to find some non obvious workaround (such as converting keys to str).

2021-02-15 00:05 UTC, phorward requested changes
Hello @hoodmane,
thanks for your work! I'm mostly well with this pull request, but what do you think about adding the failing tests as well to the test suite? See my last comment above.

2021-02-15 00:05 UTC, phorward commented on src/tests/test_typeconversions.py
> +
Can you add your failing conversion tests from [here](https://github.com/iodide-project/pyodide/pull/1244#issuecomment-778386662), so it shows that we already know about these errors and don't do any "falsification" on JavaScript objects to fit into the Python world?

2021-02-15 00:39 UTC, hoodmane commented
@phorward Thanks for the review!

2021-02-15 02:30 UTC, hoodmane commented on src/core/js2python.c
> +      // PyList_SetItem steals a reference to item no matter what
I think it's helpful to have this comment here, without it at some point I'm going to think "Why didn't I decref `item` isn't that a reference leak?" and have to look up `PyList_SetItem` in the docs to find out that it steals a reference to its argument. (I actually had to look at the source of `PyList_SetItem` to check that it always `DECREF`s the item, even if an early error occurs.)

2021-02-15 08:41 UTC, phorward approved these changes
OK, I'm fine with this, thanks for updating the tests!

2021-02-24 13:13 UTC, rth commented
Thanks! I have not reviewed the JS code in detail but the tests look good. Merging with a +1.

2021-02-24 13:13 UTC, merged